-- Generated by tools/embed.lua from GUIDE.md. Do not edit.
return [[# Designing and Writing Software in Wordlet

This is a guide to design and naming in Wordlet, not a grammar. `syntax.md` is the
surface contract and the semantic decisions behind it; `README.md` states exactly
what the compiler runs today. The examples here are written to those rules.

Two conventions keep the examples readable:

- `...` marks an elided body, not something a parser accepts.
- A **named definition must annotate every parameter**, though adjacent names may
  share one annotation, so `(a, b, x: u32)` declares three `u32` parameters
  (`syntax.md` §2). A list such as `resize(width, height, image)` is a requirement
  shape or a call site, not a definition.

The relevant section of `syntax.md` is cited where a rule is subtle enough to
change how something should be designed.

## Contents

1. [The Wordlet mindset](#1-the-wordlet-mindset)
2. [Start software design by finding the words](#2-start-software-design-by-finding-the-words)
3. [Naming is architecture](#3-naming-is-architecture)
4. [Think in requirements and supply](#4-think-in-requirements-and-supply)
5. [Ordered and keyed requirements are equal design choices](#5-ordered-and-keyed-requirements-are-equal-design-choices)
6. [Prefer keyed aggregates when positional application becomes ambiguous](#6-prefer-keyed-aggregates-when-positional-application-becomes-ambiguous)
7. [Arrange ordered requirements by binding-time structure](#7-arrange-ordered-requirements-by-binding-time-structure)
8. [Specialization is not a separate programming mode](#8-specialization-is-not-a-separate-programming-mode)
9. [Types are specialization inputs, not a separate generic language](#9-types-are-specialization-inputs-not-a-separate-generic-language)
10. [Known aggregate members should disappear when appropriate](#10-known-aggregate-members-should-disappear-when-appropriate)
11. [Treat the whole program as the outermost word](#11-treat-the-whole-program-as-the-outermost-word)
12. [The real runtime boundary is uncertainty](#12-the-real-runtime-boundary-is-uncertainty)
13. [Control specialization by controlling binding time](#13-control-specialization-by-controlling-binding-time)
14. [Known code should remain known](#14-known-code-should-remain-known)
15. [CPS is a major Wordlet design pattern](#15-cps-is-a-major-wordlet-design-pattern)
16. [Use CPS to keep borrowed state where it belongs](#16-use-cps-to-keep-borrowed-state-where-it-belongs)
17. [Tail position is architectural](#17-tail-position-is-architectural)
18. [Use sums and keyed handlers instead of artificial class hierarchies](#18-use-sums-and-keyed-handlers-instead-of-artificial-class-hierarchies)
19. [Distinguish real semantic differences instead of maximizing uniformity](#19-distinguish-real-semantic-differences-instead-of-maximizing-uniformity)
20. [Prefer scoped computation over transferring ownership unnecessarily](#20-prefer-scoped-computation-over-transferring-ownership-unnecessarily)
21. [Modules should expose vocabulary, not implementation debris](#21-modules-should-expose-vocabulary-not-implementation-debris)
22. [Do not translate foreign design patterns literally](#22-do-not-translate-foreign-design-patterns-literally)
23. [Do not optimize abstractions; try to erase them](#23-do-not-optimize-abstractions-try-to-erase-them)
24. [Architecture should reveal binding time](#24-architecture-should-reveal-binding-time)
25. [A practical design workflow](#25-a-practical-design-workflow)
26. [Questions to ask during code review](#26-questions-to-ask-during-code-review)
27. [Wordlet naming rules](#27-wordlet-naming-rules)
28. [Handlers as requirements: hierarchical continuation wiring](#28-handlers-as-requirements-hierarchical-continuation-wiring)
29. [The central Wordlet instinct](#29-the-central-wordlet-instinct)

---

## 1. The Wordlet mindset

Wordlet should not be approached as C, Rust, C++, Java, or a functional language
with different syntax.

Its fundamental design object is the **word**.

A word has requirements, those requirements may be ordered or keyed, and supplying
requirements eventually reaches saturation. Saturation invokes the word's terminal
behavior. Signatures, schemas, methods, specialization, construction and execution
are variations on this model rather than unrelated language mechanisms.

The first question when designing something in Wordlet should therefore usually
not be:

> What class, interface, trait, factory or framework abstraction should represent this?

Ask instead:

> What is the word, and what does it require?

This gives Wordlet its primary architectural instinct:

```text
problem
   ↓
find its vocabulary
   ↓
identify words
   ↓
identify their requirements
   ↓
supply what is known
   ↓
leave only genuine runtime uncertainty
```

A good Wordlet design tends to grow from its vocabulary rather than from a
pre-imposed hierarchy.

---

## 2. Start software design by finding the words

When faced with an empty project, avoid beginning with containers such as:

```text
Manager
Controller
Service
Factory
Repository
Processor
Context
```

Start by naming actual operations in the problem domain.

For an image system:

```text
decode
resize
crop
encode
save
```

For a compiler:

```text
lex
parse
check
lower
emit
```

For a network service:

```text
authenticate
authorize
route
handle
respond
```

These words already reveal a large part of the architecture.

Next, state their requirements:

```text
resize(width, height, image)
encode(format, quality, image)
authorize(policy, user, request)
```

At this stage the program already has structure without requiring a class
hierarchy, dependency-injection system, or architectural framework.

Larger structures should emerge when repeated requirements reveal that they belong
together.

---

## 3. Naming is architecture

Naming is one of the hardest problems in programming, and in Wordlet it matters
even more because **names carry much of the ontology**.

Wordlet deliberately avoids some of the syntactic categorization used by other
languages. Capitalization does not distinguish types from values or signatures from
lambdas; names are case-sensitive, but their semantic role comes from context
(`syntax.md` §1). Even the editor grammar classifies a name by position rather than
by spelling: see `editor/README.md`.

That makes names part of the architecture rather than mere decoration.

Because capitalization carries no meaning, Wordlet does not spend it. Wordlet's own
vocabulary is lowercase — `u8` through `u64`, `i32`, `i64`, `f64`, `bool`, `unit`,
`type`, and the constructors `array`, `slice`, `ref`, `ptr`, `null`, `string`,
`oneof` — and names a program introduces are lowercase `snake_case` too. The language
owns a small set of representation-level words; everything built from them earns a
domain name of its own:

```text
let document_bytes = array(u8, 4096)
let visible_text = slice(document_character)
let editor_mode = oneof { normal: unit, insert: unit, visual: unit }
let document_byte_offset = u32
```

The pressure is deliberate:

> A primitive name tells you how something is represented. A program name tells you
> what it means.

Spend names on the second. A type is just another value in the word system, so
`let document_byte_offset = u32` reads as ordinary Wordlet, and the surface language
ends up agreeing with the semantics instead of teaching a second, typographic one.
Those predefined words are also reserved at module level (`syntax.md` §1): a
module-level declaration cannot rebind `u32` or `oneof`, though a local binding may
shadow one like any outer name.

Prefer:

```text
let process_payment(
    payment: payment,
    authorization_policy: authorization_policy,
    on_authorized: (authorization): unit,
) = ...
```

over:

```text
let proc(x, p, f) = ...
```

The first version can often be understood without jumping elsewhere in the program.

### 3.1 Prefer explicit names over short names

Long names are acceptable when they remove ambiguity.

Prefer:

```text
production_configuration
payment_authorization_policy
validated_customer_address
inventory_reservation
on_payment_authorization_failed
```

over:

```text
cfg
pol
addr
res
cb
```

unless a short name is genuinely obvious in a tiny local scope.

For example:

```text
let distance(x, y: f64): f64 =
    if x < y then y - x else x - y
```

is perfectly clear.

But:

```text
let connect(c, p, t, r) = ...
```

is poor if the parameters actually mean:

```text
configuration
port
transport
retry_policy
```

A useful rule is:

> The wider the scope and the more architectural the concept, the more explicit its
> name should be.

### 3.2 Name by domain meaning, not implementation

Prefer:

```text
validated_request
payment_authorization
retry_policy
inventory_reservation
```

over:

```text
request_struct
payment_result_object
retry_callback
reservation_record
```

Implementation details change more easily than domain meaning.

A good name should describe what something **means**, not merely how it happens to
be represented today.

### 3.3 Specialized words should name what has been fixed

Specialization creates meaningful architectural concepts.

Prefer:

```text
let production_renderer = renderer {
    format = html,
    policy = production_policy,
}
```

over:

```text
let specialized_renderer_1 = ...
```

Similarly:

```text
let authenticated_request_handler = ...
let jpeg_thumbnail_encoder = ...
let database_backed_session_store = ...
```

These names tell the reader what knowledge was supplied.

### 3.4 Keys are names, so choose them carefully

Keyed aggregates amplify the importance of naming:

```text
checkout {
    inventory = inventory,
    payment_gateway = gateway,
    fraud_policy = policy,
    on_payment_declined = decline,
    on_order_confirmed = confirm,
}
```

The keys form a small vocabulary for that subsystem.

Avoid generic keys such as:

```text
handler
callback
thing
data
result
value
```

when a domain-specific name exists.

Prefer:

```text
payment_authorized
payment_declined
inventory_unavailable
order_confirmed
```

over:

```text
ok
error
handler1
handler2
```

when the more explicit names clarify the control flow.

### 3.5 Continuation names should describe exits

A continuation is often best understood as a named possible future.

Prefer:

```text
checkout {
    payment_authorized = ...,
    payment_declined = ...,
    inventory_unavailable = ...,
}
```

over:

```text
checkout {
    success = ...,
    failure = ...,
}
```

when the domain has multiple distinct outcomes.

This makes CPS-style code read almost like a protocol description.

### 3.6 Names should make intermediate architecture visible

Since `let` can name a word at any stage of specialization, use that ability
deliberately:

```text
let parse_json = parse(json)
let strict_json_parser = parse_json(strict_policy)
let production_json_parser = strict_json_parser(production_diagnostics)
```

Each name records an architectural decision.

A `let` binding should often answer:

> What meaningful thing have I created by supplying this knowledge?

### 3.7 Avoid obscure cleverness

Wordlet is already conceptually unusual.

Do not make it harder by using cryptic names, private abbreviations, or overly
compressed terminology.

Prefer code that can be read aloud as domain language.

A useful principle is:

> If a name saves three characters but costs the reader one inference, it is
> probably a bad trade.

---

## 4. Think in requirements and supply

Application in Wordlet means **supplying requirements**.

For an ordered word:

```text
let affine(a, b, x: u32): u32 =
    a * x + b
```

this:

```text
affine(4)
```

supplies one requirement.

This:

```text
affine(4, 3)
```

supplies two.

If requirements remain, the result is a specialized word. If all remaining
requirements are supplied, the terminal is invoked. Partial supply requires the
supplied arguments to be static (`syntax.md` §3).

Do not mentally divide these into two unrelated operations called "partial
application" and "calling."

The more useful model is:

```text
word
  ↓ supply
word
  ↓ supply
word
  ↓ saturation
terminal
```

Whether a particular application happens to saturate the word is a consequence of
its remaining requirements, not a different syntactic category.

---

## 5. Ordered and keyed requirements are equal design choices

A word's requirements carry either **ordered** or **keyed** identity, and the
definition chooses which. Neither is the general case: an ordered word and a keyed
word are both ordinary words, with the same supply model, the same specialization and
the same call, and a schema is simply the keyed word whose terminal constructs an
instance (`syntax.md` §2, §8).

### Ordered requirements

Use ordered requirements when position itself carries meaning:

```text
add(a, b)
resize(width, height, image)
distance(a, b)
```

```text
let affine(a, b, x: u32): u32 = a * x + b
let transform = affine(4, 3)     -- supplies two of three; a specialized word
```

Application is compact. Supplying fewer requirements than remain returns a
specialized word; supplying all of them invokes the body. Requirement order also
carries dependency, because an earlier parameter may determine a later one, as `T`
does in `let identity(T: type, x: T) = x`.

### Keyed requirements

Use keyed requirements when the names carry meaning:

```text
let distance { x: u32, y: u32 }: u32 = x * x + y * y
let d = distance { x = 3, y = 4 }
```

Same model, different identity: supplying fewer keys returns a specialized word,
supplying every key invokes the body, and a partial supply needs static values. Keys
have no order, so supplies may be written in any order:

```text
let near = distance { y = 4 }     -- a specialized word awaiting x
let d = near { x = 3 }            -- 25
let same = distance { y = 4, x = 3 }
```

Every key is annotated, because a key has no position to infer a type from.

A schema is the same mechanism with a construction terminal, so `distance { ... }`
and `server { ... }` are one thing:

```text
let server = {
    host: host,
    port: u32,
    logger: logger,
    clock: clock,
    retry: retry_policy,
}

let production_server = server {
    logger = production_logger,
    retry = production_retry,
}
```

### The choice is the design

Ordered and keyed requirements are not two features. They are two identities for the
same requirement, and both specialize and lower the same way: a keyed supply is
reordered into the word's declaration order and invoked as an ordinary call, so
nothing about it survives to runtime that an ordered call would not.

What differs is how the call **reads**. An ordered call reads as an *operator*, so it
fits requirements that are operands: few, fixed, and in an order the reader already
knows.

```text
add(a, b)          lerp(a, b, t)          clamp(x, low, high)
resize(width, height, image)              distance(a, b)
```

A keyed call reads as a *record*, so it fits requirements that are configuration or
capabilities: independent, often same-typed, and named for a reason.

```text
render { width = w, height = h, scene = scene, camera = camera }
server { host = host, port = port, logger = logger, clock = clock, retry = retry }
```

The quick test is whether you can read the call aloud without the parameter names.
`lerp(a, b, t)` works; `render(w, h, sc, cam)` does not.

The definition decides, and that is the point: an ordered word cannot be called by
name, so its interface commits every call site to operands. A keyed word may still be
called positionally when every key is supplied (`distance(3, 4)`), because the order is
its declaration order, but it can never be supplied partially by position. So `()` and
`{}` are not interchangeable spellings at a call site; they are two interfaces a
definition chooses between, and choosing is choosing how the call reads everywhere.

```text
Use () when position communicates enough.
Use {} when names communicate essential structure.
```

Both are first class; neither is a fallback for the other, and a schema is just the
keyed word that constructs.

---

## 6. Prefer keyed aggregates when positional application becomes ambiguous

A call like:

```text
run(db, logger, retry, clock, on_error, on_done)
```

places a large cognitive burden on ordering.

A keyed design makes the architecture visible:

```text
Run {
    database = database,
    logger = logger,
    retry_policy = retry_policy,
    clock = clock,
    on_processing_failed = processing_failed,
    on_processing_completed = processing_completed,
}
```

The aggregate simultaneously documents the requirements and makes independent
specialization natural.

A useful design signal is therefore:

> If you are constantly asking what argument number five means, the requirements
> probably want keys.

Keyed words are especially suitable for:

- configuration,
- capabilities,
- environments,
- policies,
- sets of handlers,
- protocol operations,
- continuations,
- construction of structured data.

They are also valuable because field order does not define schema identity.

---

## 7. Arrange ordered requirements by binding-time structure

For ordered words, parameter order carries architectural information.

A useful default is:

```text
structural / least variable
        ↓
type
algorithm
policy
configuration
        ↓
ordinary dynamic parameters
        ↓
per-call input
most variable
```

For example:

```text
let transform(t: type, algorithm: algorithm, policy: policy, input: t) = ...
```

This ordering makes progressive specialization natural.

It also agrees with Wordlet's dependent requirement model: requirements are
evaluated left-to-right, and an earlier parameter may determine a later requirement
(`syntax.md` §2):

```text
let identity(t: type, x: t) = x
```

Here `T` must be known before `x` can be checked.

This is a heuristic, not a law.

If several requirements are independent enough that imposing an ordering becomes
artificial, use keyed requirements instead.

---

## 8. Specialization is not a separate programming mode

Do not think of Wordlet as having ordinary programming plus a special
metaprogramming subsystem.

Known information naturally participates in specialization.

For example:

```text
let affine(a, b, x: u32): u32 =
    a * x + b

let transform = affine(4, 3)
```

But explicit partial application is not required for specialization.

A saturated invocation such as:

```text
affine(4, 3, x)
```

may share the same residual specialization as:

```text
let transform = affine(4, 3)
transform(x)
```

when the same information is known.

Therefore do not ask:

> Is this expression a specialization or a call?

Ask:

> Which parts of this invocation are known, and which parts must survive to runtime?

This is one of Wordlet's central design instincts.

---

## 9. Types are specialization inputs, not a separate generic language

Generic programming should usually remain ordinary word programming.

```text
let identity(t: type, x: t) = x

let twice(t: type, f: (t): t, x: t) =
    f(f(x))

let identity_u32 = identity(u32)
```

`type` is compile-time information (`syntax.md` §10). There is no separate implicit
generic parameter mechanism.

This means a Wordlet programmer should resist immediately inventing separate
abstractions for:

```text
templates
generic classes
generic traits
constexpr types
type-level functions
```

First try an ordinary word taking `type`.

If ordinary supply and specialization already express the idea, another language
feature is unnecessary.

One boundary is worth remembering early: a word with a `type` parameter has no
closed runtime ABI, so it cannot itself be exported as a function. Specialize it
first, then export the specialization:

```text
let identity_u32 = identity(u32)   -- export this, not `identity`
```

A runtime value cannot supply `type`, and a public callable signature must be
closed (`syntax.md` §10).

---

## 10. Known aggregate members should disappear when appropriate

Partial keyed supply can make structural knowledge static:

```text
let point = {
    x: u32,
    y: u32,
}

let at_x3 = point {
    x = 3,
}
```

`x` is now part of the specialized schema.

A use of that field can therefore resolve to the known value instead of
necessarily becoming a runtime load. For `at_x3 { y = 4 }.x`, the compiler emits the
constant directly.

But distinguish this from ordinary saturated construction:

```text
let p = point {
    x = 3,
    y = 4,
}
```

Here `p.x` and `p.y` are instance storage. They happen to have known initial
values, but they are not thereby readonly specialization parameters. The
specification deliberately preserves this distinction.

A useful mental model is:

```text
partial keyed supply
    → structural knowledge

saturated construction
    → runtime instance
```

---

## 11. Treat the whole program as the outermost word

A useful Wordlet design interpretation is to regard the program itself as the
outermost word.

Compilation progressively supplies everything that can be known before execution.

What remains is the residual program.

Conceptually:

```text
Program
   ↓ configuration
   ↓ types
   ↓ algorithms
   ↓ policies
   ↓ known continuations
   ↓ constants
   ↓ static structure

ResidualProgram(runtime_input)
```

A `.let` file may define `main` as its program entry, in which case `main` is the
sole export when no explicit module export configuration is given (`syntax.md`
§11).

The implementation itself reflects this worldview: normalization evaluates known
computation, whereas residual mode emits IR for computation that must remain.

Compilation can therefore be thought of as:

> specialize the program against the world known at compilation time.

---

## 12. The real runtime boundary is uncertainty

Runtime should contain what genuinely cannot be known beforehand.

Typical sources include:

```text
program inputs
extern results and effects
mutable runtime storage
runtime-dependent control flow
genuinely unknown callable implementations
```

`extern` is an especially clear boundary. A foreign call is an effect the compiler
cannot inspect, and even constant arguments do not make that call foldable
(`syntax.md` §8.6).

Therefore:

```text
extern let read_sensor(): u32

let scale(k, x: u32): u32 = k * x
let scale100 = scale(100)

let main(): u32 =
    scale100(read_sensor())
```

should be understood as:

```text
everything except the sensor result is potentially removable before runtime
```

The fastest code is often the code that never reaches the residual program.

---

## 13. Control specialization by controlling binding time

Specialization is valuable until a dimension has too many possible static values.

Suppose:

```text
let process(mode: mode, threshold: u32, input: input) = ...
```

If `mode` has three possibilities but `threshold` has millions, specializing both
dimensions may create unnecessary residual instances.

Prefer:

```text
mode       → static
threshold  → runtime
input      → runtime
```

The important mechanism is **not** merely using a saturated call. Known values in
saturated calls can still specialize.

To move a dimension to runtime, arrange for its value to come from a runtime
parameter, foreign result, mutable runtime state, or another runtime computation.

For example:

```text
let scale(n, x: u32): u32 = n * x

let run(n, x: u32): u32 =
    scale(n, x)
```

Inside the residual `run`, `n` is runtime information rather than a distinct
specialization value.

The implementation's specialization key distinguishes static arguments from
ordinary runtime positions, and its depth diagnostic names the remedy when
specialization nests too far:

> a recursive word whose static arguments change specializes once per value, so
> bind the changing value at run time

The general rule is:

> If specialization explodes, do not abandon the word. Move the explosive
> requirement across the runtime boundary.

---

## 14. Known code should remain known

Higher-order programming does not automatically imply dynamic dispatch.

When callable identity is known, Wordlet can specialize around that code.

Only genuinely runtime-unknown implementations require runtime callable
representations. Wordlet's callable model deliberately derives this from binding
time rather than from a separate `dyn`-style declaration (`syntax.md` §9).

Therefore prefer ordinary higher-order composition:

```text
let with_logging(
    logger: logger,
    operation: operation,
    input: input,
): result = ...
```

rather than introducing a callback framework or polymorphic interface merely
because code is being passed as data.

Ask:

> Is the implementation genuinely unknown at runtime?

If no, preserve its identity and allow specialization to remove the abstraction.

---

## 15. CPS is a major Wordlet design pattern

Continuation-passing style fits Wordlet unusually well.

Instead of returning something whose lifetime or ownership becomes difficult, keep
control within the owning activation:

```text
process(input) {
    processing_completed = |value| -> ...,
    validation_failed = |error| -> ...,
}
```

Keyed continuation sets are especially readable because the key names the exit.

This can solve several classes of architectural problem using ordinary words:

```text
success / failure flow
state-machine transitions
resource-local computation
error handling
protocol branching
visitor-like dispatch
ownership-sensitive computation
stack-safe recursive structure
```

The important idea is that a continuation is just another callable requirement.

If it is statically known, it can specialize into the surrounding computation
rather than necessarily becoming a heap callback or indirect function call.

The handler keys are the alternatives of a sum, and the match is exhaustive
(`syntax.md` §8.1). A complete shape makes the connection visible:

```text
let outcome = oneof {
    processing_completed: completed,
    validation_failed: validation_error,
}

let run(input: input): u32 =
    process(input) {
        processing_completed = |completed: completed| -> completed.count,
        validation_failed = |error: validation_error| -> 0,
    }
```

---

## 16. Use CPS to keep borrowed state where it belongs

Wordlet deliberately restricts borrowed closures and references from escaping
storage that does not outlive them. Borrowed closures and method values can be used
locally or passed through non-retaining callable interfaces, but cannot simply be
returned or stored as though they owned their environments (`syntax.md` §9).

Instead of:

```text
create borrowed thing
return borrowed thing
hope its owner survives
```

prefer:

```text
create borrowed thing
invoke continuation while owner is alive
```

That turns many awkward ownership problems into control-flow structure.

Do not use CPS merely because it is fashionable. Use it when controlling *where
computation continues* is more natural than transferring ownership of intermediate
state.

---

## 17. Tail position is architectural

Wordlet recognizes a tail self-call to the currently built residual instance and
can turn it into a loop back-edge when the conditions permit (`syntax.md` §10).

That makes tail-oriented decomposition and CPS valuable for computations that
would otherwise grow the stack.

Prefer structures conceptually like:

```text
step(state)
    → step(next_state)
    → step(next_state)
    → done(result)
```

over recursion where every frame must resume afterward.

But be precise about the current guarantee: the implementation optimizes
same-instance tail self-calls. Do not assume this automatically means unrestricted
proper-tail-call optimization across all mutually recursive continuations. A keyed
self-call counts too: `f { k = v, ... }` that supplies every key is a tail call
exactly as `f(v, ...)` is, so a keyed word loops the same way; a partial keyed
supply only returns a specialized word and is not a call.

Also remember that `defer` can intentionally prevent tail-loop conversion because
deferred work must happen after the call returns (`syntax.md` §8.8).

### Threaded dispatch is reified-continuation CPS

For an interpreter or any dynamic dispatch, the continuation should be **data**. A
keyed match whose handler lambdas call the loop is a *different code instance*, so
that call is an ordinary call and the stack grows one frame per step. Return the
next state from the handlers instead, and let one tail self-call in the loop word's
own body drive it:

```text
let advance(m: machine): machine =
  m.code[m.pc] {
    push = |value: u32| -> do ... return m end,
    add  = |unit: unit| -> do ... return m end,
    halt = |unit: unit| -> do m.done = true return m end,
  }

let run(m: machine): u32 = do
  let next = advance(m)
  if next.done then return next.result end
  return run(next)
end
```

`run(next)` is in `run`'s own tail position, so it lowers to
`for (;;) { ... continue; }`; the handler lambdas only return a machine, so they
never stay on the stack after their step. `examples/dispatch.let` is this shape.

Prefer the hot state as the loop's **parameters** rather than a record: a code
`ptr`, the `pc`, a stack `ptr` and `sp` are one word each, so a step copies no
aggregate at all, and the handlers return the transition instead of the machine.
`examples/interpreter.let` is that form — one back edge, no per-step copy.

An opaque match lowers to a C `switch` on the tag, with the last alternative as
`default`, so the branch is total. A small opcode set becomes a couple of compares;
a dozen arms that do distinct work compile to one `jmp *` jump table, which is
O(1) dispatch rather than a chain of compares. The switch is the reason a Wordlet
interpreter stays fast as the opcode set grows.

The choice is binding time, not syntax. A handler set known at compile time becomes
direct, specialised code — a tag test with the arm inlined — while a handler set
that arrives at run time becomes the callable ABI, an invocation pointer, which is
classic indirect threading. Moving a dimension to run time is the same move that
controls specialization (section 13): make its value come from a parameter, a
foreign result or mutable storage.

---

## 18. Use sums and keyed handlers instead of artificial class hierarchies

Wordlet's `oneof` builds sum types from keyed alternatives:

```text
let shape = oneof {
    circle: circle,
    rectangle: rectangle,
}
```

Matching is itself keyed application:

```text
shape {
    circle = |circle: circle| -> ...,
    rectangle = |rectangle: rectangle| -> ...,
}
```

Every alternative must be handled. Known alternatives can select their handler
directly; runtime alternatives become runtime tag tests (`syntax.md` §8.1).

Before reaching for an inheritance-like representation, ask:

> Is this actually a closed set of alternatives?

If yes, a sum plus keyed handlers often states the domain more directly.

---

## 19. Distinguish real semantic differences instead of maximizing uniformity

Wordlet's small ontology does not mean collapsing concepts that carry genuinely
different guarantees.

`ref(T)` and `ptr(T)` are intentionally different.

A `ref` is checked: its target must outlive its use.

A `ptr` deliberately carries no such lifetime guarantee. It may be null or
dangling; the programmer is responsible (`syntax.md` §8.5).

This illustrates an important design principle:

> Unify mechanisms that differ only accidentally. Keep separate mechanisms when
> they express different guarantees.

Semantic compression is useful.

Semantic erasure is not.

---

## 20. Prefer scoped computation over transferring ownership unnecessarily

Resources can often remain local to the computation that uses them.

The specification demonstrates this with ordinary higher-order words that acquire
a resource, invoke a body, release the resource and return the result
(`syntax.md` §8.7). Known body code can specialize into that combinator.

`defer` provides a direct lexical release mechanism when that shape is preferable
(`syntax.md` §8.8).

This suggests another Wordlet instinct:

> Before inventing an ownership-bearing object, ask whether the operation can
> remain inside a scoped word.

CPS and scoped combinators frequently complement each other.

---

## 21. Modules should expose vocabulary, not implementation debris

A module exports exactly the names it chooses to expose; non-exported names remain
private. Used modules are resolved as namespaces, and modules compiled together
share the generated translation unit and initialization machinery (`syntax.md`
§11).

Treat module exports as the public vocabulary of a subsystem.

Prefer:

```text
parse
validate
compile
document
compilation_error
```

over exposing every helper introduced during implementation.

A module boundary should make the system easier to speak about.

Names at module boundaries deserve particular care because they become the
language other modules use to describe the subsystem. Two practical reminders:

- A generic word taking `type` cannot itself be exported; export a specialization
  (see §9).
- The export configuration is not a runtime record. It is compile-time module
  metadata, and its sections are only `types`, `functions` and `results`.

---

## 22. Do not translate foreign design patterns literally

A programmer arriving from another ecosystem will naturally try to reproduce
familiar mechanisms.

Be suspicious of immediate translations such as:

| Foreign pattern | Naive Wordlet translation |
| --- | --- |
| class | schema with lots of machinery |
| interface | runtime callable everywhere |
| factory | constructor abstraction |
| dependency injection | service container |
| generic class | custom type machinery |
| strategy object | stored runtime callable |
| visitor | class hierarchy |

Ask whether the actual requirement can instead be expressed through:

```text
ordinary word
ordered supply
keyed supply
type argument
sum
known callable
continuation
scoped computation
specialization
```

Many traditional design patterns exist partly to compensate for limitations in the
host language's ontology.

Wordlet has different limitations and therefore should develop different patterns.

---

## 23. Do not optimize abstractions; try to erase them

A useful Wordlet performance principle is:

> The fastest code is the code the runtime never executes.

Instead of asking first:

> How cheap is this abstraction?

ask:

> Does this abstraction need to survive specialization?

Known configuration can disappear.

Known policy branches can disappear.

Known callable dispatch can disappear.

Known type decisions can disappear.

Known aggregate members can disappear.

Known computation can disappear entirely.

The residual program should increasingly resemble the irreducible computation
demanded by runtime input and effects.

---

## 24. Architecture should reveal binding time

A good Wordlet architecture communicates not only data flow but *when information
becomes known*.

For example:

```text
let engine = {
    algorithm: algorithm,
    logger: logger,
    limit: u32,
}

let production_engine = engine {
    algorithm = fast_algorithm,
    logger = production_logger,
}
```

This says something architectural:

```text
algorithm → deployment/static decision
logger    → deployment/static decision
limit     → instance/runtime decision
```

That distinction is useful even before considering optimization.

Binding time is part of the design.

Names should reinforce it:

```text
production_engine
debug_engine
fixed_size_packet_decoder
runtime_configured_packet_decoder
```

rather than hiding the distinction behind generic names.

---

## 25. A practical design workflow

When starting a Wordlet system:

1. Write the vocabulary of the domain as clearly named words.
2. Prefer explicit domain terminology over abbreviated implementation terminology.
3. Identify each word's requirements.
4. Decide whether requirement identity is positional or keyed.
5. Give keys names that explain their semantic role.
6. Put structural/dependent requirements early in ordered words.
7. Use `type` arguments instead of inventing separate generic machinery, and
   specialize before exporting.
8. Partially supply stable information naturally.
9. Give specialized words names describing what has been fixed.
10. Keep high-cardinality or rapidly changing information runtime.
11. Prefer known callable composition over premature runtime polymorphism.
12. Consider keyed continuations where control-flow exits have meaningful names.
13. Name continuations after domain outcomes rather than generic `ok`/`error` when
    useful.
14. Use CPS when it keeps borrowed state local or prevents stack growth.
15. Use sums for genuine closed alternatives.
16. Use `ref` only when its lifetime guarantee is meaningful; use `ptr` when
    deliberately crossing into unchecked address semantics.
17. Keep resources scoped where practical.
18. Keep module exports small, explicit and domain-oriented.
19. Inspect what residual computation remains.
20. If too much machinery survives runtime, reconsider which requirements could
    have been supplied earlier.
21. If specialization explodes, move the offending dimension later into runtime.

---

## 26. Questions to ask during code review

A useful Wordlet review is less about whether a known design pattern was followed
and more about whether the program's vocabulary, requirements and binding times are
expressed honestly.

Ask:

```text
What is the word here?

Does its name describe domain meaning clearly?

Would a longer name remove ambiguity?

Are any abbreviations forcing the reader to remember private vocabulary?

What are its requirements?

Should these requirements be ordered or keyed?

Do keyed requirements have meaningful, explicit names?

Does parameter order communicate dependency and binding time?

Which requirements are actually static?

Which are genuinely runtime?

Are we accidentally specializing a high-cardinality value?

Are we accidentally making known code dynamic?

Does the specialized word's name explain what was fixed?

Could this runtime configuration be keyed specialization?

Could this returned borrowed object instead become a scoped continuation?

Could CPS make this control flow clearer or stack-safe?

Do continuation names describe actual domain outcomes?

Could a sum express these alternatives more directly?

Does this abstraction need runtime representation at all?

Does the module expose meaningful vocabulary or implementation debris?

What remains after specialization, and why?
```

---

## 27. Wordlet naming rules

A compact naming style for Wordlet.

### Spell names in lowercase `snake_case`

Wordlet's own words are lowercase, and so are the names a program introduces:

```text
document_byte_offset
terminal_column
visible_document_lines
command_arguments
```

Capitalization is not carrying a category here, so there is no reason to spend it. A
name spelled `DocumentByteOffset` would suggest a type/value distinction the language
does not make.

### Name the meaning, not the representation

Two values can share a machine representation and still be different ideas:

```text
document_byte_offset
cursor_position
viewport_origin
selection_anchor
search_match_position
```

Even when an alias resolves to the same `u32`, the name is what keeps them from being
substituted for one another by mistake. The same applies to types built from a
primitive:

```text
let document_bytes = array(u8, 4096)
let terminal_cells = array(terminal_render_cell, 80 * 24)
```

rather than a program that keeps saying `array` and `u8` long after the meaning was
known.

### Let the containing type supply the context

An alternative lives inside its sum, so it does not need to repeat it:

```text
editor_mode.normal
editor_mode.insert
```

not `EDITOR_MODE_NORMAL`, `NormalMode` or `EditorModeNormal`. The containing type
already said which mode this is.

### Name outcomes for why control arrived

A callable's name should say why it was reached, not what mechanism delivered it.
Prefer:

```text
save_requested
document_saved
document_save_failed
```

over `on_save`, `callback`, or `save_handler`. The first group describes the
occurrence; the second describes the plumbing.

### Avoid machinery suffixes

Names like these describe the implementation language, not the domain:

```text
Manager  Factory  Impl  Interface  Base  Abstract
DTO  Controller  Service  Callback  Handler  Object  Class
```

Use them only when they are genuinely part of the domain architecture, and prefer a
capability name when they are not: `load_customer` and `store_customer` over
`customer_repository`.

### Qualify only to remove a real ambiguity

Context should do most of the work. `column` inside terminal-specific code is clearer
than `terminal_column` repeated everywhere; `terminal_column` is better when the file
also deals with document columns. Qualify against a confusion the reader could
actually make, not against one that no longer exists in that scope.

### A descriptive name buys clarity, not a guarantee

Naming is architecture, but it is not checking. Two aliases with different names are
still the same type to the compiler. A callable field named `save_requested` is still
just a callable that may return normally; its name does not make it asynchronous, nor
does it prove it never returns to its caller. A `ptr(u8)` called
`terminal_input_buffer` is named better and is exactly as unchecked as before; the
wrapper is what has to establish the length and lifetime. Use names to make intent
obvious, and use the type system, ownership rules and tests to make it true.

### Prefer clarity over brevity

```text
payment_authorization_policy
```

is usually better than:

```text
auth_pol
```

### Prefer domain names over technical wrappers

```text
validated_order
```

is usually better than:

```text
order_result_record
```

### Let scope determine acceptable brevity

```text
x
y
i
```

are fine where their meaning is immediate.

They are poor architectural names.

### Name keyed requirements for what they mean

```text
retry_policy
database
clock
on_inventory_unavailable
```

not:

```text
config1
service2
handler
callback
```

### Name continuations for their destination or outcome

```text
payment_authorized
payment_declined
inventory_unavailable
```

### Name specializations for the knowledge they contain

```text
production_renderer
jpeg_thumbnail_encoder
strict_json_parser
```

### Avoid implementation names unless implementation is the meaning

Prefer:

```text
customer_repository
```

only if "repository" is genuinely part of the domain architecture.

Otherwise a more direct capability name may be clearer:

```text
load_customer
store_customer
```

### Do not be afraid of long names

Wordlet removes a great deal of structural ceremony.

Use some of that saved visual space for names that communicate meaning.

---

## 28. Handlers as requirements: hierarchical continuation wiring

An Elm-style architecture centers on one global model, messages and an update
function:

```text
Model → View → Message → Update → Model
```

That predicts beautifully, and it converges on a fairly global notion of state and
message routing. Wordlet's shape is different:

```text
Parent word
├── owns parent state
├── owns and wires ChildA
├── owns and wires ChildB
├── supplies requirements downward
└── supplies continuations downward

Child
├── owns its local state
├── computes locally
└── reaches the outside only through supplied continuations
```

So the architecture is not "data flows one way". It is **hierarchical control-flow
composition under lexical ownership**. The child does not emit an untyped message
into a global update; it receives an explicit contract, and the parent decides what
each exit means:

```text
editor {
    document_changed = update_document_state,
    save_requested = save_current_document,
    close_requested = close_editor,
}
```

The property that follows is stronger than "messages flow upward":

> A child can only affect the outside world through capabilities the parent
> explicitly supplied.

That is a capability property — the absence of *ambient authority*. A child cannot
reach navigation, persistence or a sibling unless it is given a word that provides
that capability. It is a discipline, not enforcement: nothing stops a parent from
supplying too much, so a review question is whether each child receives exactly the
capabilities its named exits mention.

### This is the handler-in-scope half of algebraic effects

A child's requirements *are* an effect signature, and the parent's supply is the
handler:

```text
let admit(
    request: request,
    on_admitted: (accepted): unit,
    on_denied: (rejected): unit,
): unit = ...
```

`on_admitted` and `on_denied` are the operations the child may perform; the parent
supplies their meaning. Keyed application is the `match` that dispatches an outcome,
and keyed supply is how a handler set is built. What Wordlet does *not* add is a
resumable, first-class continuation: the child's "perform" is an ordinary call, so
no continuation is captured, and a handler whose identity is known specializes into
the call site — an inlined effect handler. The callable distinction is the same
lever: known code is a direct call, a handler that arrives at run time is the
callable ABI.

### The two directions are duals

Capabilities travel downward and outcomes travel upward, and both are
continuations:

- **Downward:** the parent supplies words and the child calls them. Use it when the
  exit happens inside the owner's activation.
- **Upward:** the child returns a sum and the parent dispatches it. Use it when the
  exit must be deferred, stored, or cross a boundary.

The ownership model decides which is available. A borrowed closure cannot escape, so
a capability the child keeps past the owner's activation has to be owned code or a
value it returns. That is not friction — it is the type system enforcing the
containment the pattern wants. `borrow-escape` and `ref-escape` become architectural
diagnostics: they fire precisely when a child tried to keep authority past its
owner's lifetime.

`examples/pipeline.let` shows one child serving both directions through an
`R: type` parameter: `settle` supplies exits that yield a scalar, `evaluate` returns
the outcome as a sum, and `summarize` dispatches it.

### State ownership and architectural ownership point the same way

A child can own real mutable state without every transition becoming a global
message:

```text
let editor = {
    cursor: u32,
    selection: u32,
    ...
}
```

and operate on it directly; only what is architecturally meaningful crosses the
boundary. So you do not have to choose between "everything is globally immutable
data" and "everything has a pointer to everything else". You get **local mutable
ownership with explicit continuation boundaries**.

Methods borrow actual receivers, and nested lexical owners use the actual enclosing
records rather than invented parent pointers, so the architecture tree and the
storage tree are the same tree. Siblings share only through an owner reference or
module storage, and both reintroduce the coupling the pattern otherwise keeps out —
which is why they should be deliberate.

### Where it is honest about its limits

- **Componentized source, connected control flow — while handlers are known.** Once
  a handler crosses an export or arrives from the host it becomes the callable ABI,
  an invocation pointer. The design survives; the erasure does not. That is the same
  binding-time lever as specialization (section 13).
- **Continuation chains are stack, not loops.** Parent → child → parent is mutual
  recursion between instances, so only a same-instance tail self-call becomes a back
  edge. Shallow trees are fine; a deep synchronous chain needs a trampoline
  (section 17).
- **Sums are closed, which is both the point and the limit.** A child's outcome set
  is exhaustively handled, which is what makes the wiring readable. Open extension —
  plugins, third-party messages — needs a signature or ABI boundary and gives up the
  exhaustive match.
- **A child's state is tree-shaped by value.** Records copy on pass and return, so a
  parent that wants a child to mutate shared state passes a place — a method
  receiver or an enclosing owner — not a copy. `ref` to a sibling local is rejected
  on purpose (`syntax.md` §8.2).

### The same shape outside UI

The compiler in this repository is the pattern:

```text
parse(source, on_parsed, on_syntax_error)
check(ast, on_checked, on_type_error)
lower(checked, on_lowered, on_unresolved)
```

Each stage owns its cursor and tables, exposes only named exits, and the parent
decides what each exit means. There is no global compiler-state object and no event
bus; and because the handlers are known code the wiring specializes into direct
calls, so the residual program looks far more like straight-line control flow than
the component structure suggests. A server (`authenticated`, `unauthorized`,
`malformed_request`, `internal_failure`) and a game (`Scene`, `Player`, `Inventory`,
`Dialog`, `Combat`) have the same shape.

### The principle

> Parents own and compose stateful children; children expose only named
> continuation points, and parents supply the computations attached to those points.

This guide calls the mechanism **handlers as requirements**: a child's exits are
requirements, and the pattern is how parents wire them. The design question is not
"what event does this component emit?" but "what words does this child require, and
who supplies them?"

---

## 29. The central Wordlet instinct

Wordlet's design style can ultimately be condensed to:

```text
Name the words clearly.
State their requirements.
Use positions when order carries meaning.
Use keys when names carry meaning.
Let names expose domain structure.
Supply knowledge as soon as it is useful.
Leave uncertainty until runtime.
Keep known code known.
Pass control when transferring ownership is awkward.
Let specialization erase abstractions.
```

The point is not to minimize syntax for its own sake.

The point is to obtain **semantic compression**: a small collection of meaningful
mechanisms that compose into solutions for generics, configuration, construction,
higher-order programming, dependency provision, state machines, continuations,
resource scopes and other recurring software-design problems.

Wordlet is therefore opinionated, but not because it mandates a particular
architecture.

It is opinionated because it encourages a particular way of seeing software:

> A program is a progressively supplied network of clearly named words, and runtime
> should contain only what could not meaningfully have been decided earlier.

The language removes many categories and much ceremony.

That makes names more important, not less.

**Names are where the architecture becomes visible.**
]]
