-- Generated by tools/embed.lua from syntax.md. Do not edit.
return [==[# Wordlet — syntax and semantic contract

Wordlet owns its syntax. This document specifies the surface language for `architecture.md`.
Examples are specification examples, not claims that a parser/compiler already implements them.

The core is a word with ordered or keyed requirements, an optional result contract, and an optional
terminal. Application supplies requirements; saturation invokes an implementation. A signature has
requirements and a result contract but no implementation. A record schema has keyed requirements
and an intrinsic construction terminal. A method is an executable word with an implicitly bound
actual receiver.

Owning syntax changes application and control-flow elaboration, not just punctuation. This document
makes those changes explicit. There is no compatibility requirement with the old Lua grammar.

## 1. Lexical rules and item boundaries

The grammar is free-form. Newlines and indentation are whitespace. A `--` comment runs to the end
of the line and is otherwise whitespace. `--` immediately followed by a long bracket (below) is a
block comment instead, so a comment may span lines and may contain anything; a `--` followed by a
space is always the line form, so `-- [[1, 2]]` comments out a bracket. Keywords and delimiters
determine structure. Semicolons are optional separators between complete statements/declarations, not within
expressions. Commas separate parameters, arguments, fields and result-list items; trailing commas
are allowed in delimited lists.

Identifiers use ASCII letters or underscore followed by ASCII letters, digits or underscore. Names
are case-sensitive; capitalization never distinguishes a type from a value or a signature from a
lambda. Reserved keywords are `let`, `extern`, `do`, `defer`, `end`, `if`, `then`, `else`, `return`, `and`, `or`, `not`,
`true`, and `false`. Primitive names U32, U8, U16, I32, U64, I64, F64, Bool, Unit and Type are
predefined bindings, as are the type constructors `OneOf` (section 8.1), `Ref` (section 8.2), `Array`
and `Slice` (sections 8.3 and 8.4), `Ptr` (section 8.5) and the null pointer `Null` (section 8.5).

Numeric literals are decimal, hexadecimal prefixed by 0x, or binary prefixed by 0b. A single
underscore may separate any two digits, so 1_000_000 and 0b1010_1010 read as they look; a separator
that leads, trails or doubles rejects rather than being ignored into a different value. A literal
that fits a
word is a U32 and one that does not is a U64, so 0xFFFFFFFFFFFFFFFF can be written directly; a
literal above 64 bits rejects rather than wrapping. A leading minus is an operator, not part of a
literal. There are no nil or implicit tuple literals. A string literal is a byte sequence, specified in
section 8.4.

The integer types are `U8`, `U16`, `U32`, `I32`, `U64` and `I64`. `I32` is
two's complement, so it wraps, its division truncates toward zero with the remainder taking the
dividend's sign, its right shift is arithmetic, and the most negative value divided by -1 wraps to
itself rather than being undefined. Its negation wraps too, and a signed power needs a power that is
not negative (a run-time one is checked).

An operation needs one integer type unless one operand is a literal, which adopts the other's type
when its value fits; mixed widths of one signedness widen to the wider one, and mixing signed and
unsigned rejects, so a conversion has to say which is meant. Changing signedness at one width
reinterprets the bits; any other conversion that cannot lose a value is implicit, and one that can is
checked, rejecting a known value outside the target and stopping a run-time one.

Arithmetic wraps at the width its type names, comparisons widen first, and a shift amount is a plain
U32. Assigning a run-time value to a narrower annotation rejects (`numeric-range`) rather than
truncating it silently.

`U64` and `I64` are 64 bits wide and follow the same rules, including the `I64` boundary cases above.
Their bounds are not Lua numbers, so a conversion that changes width is checked against the target's
range rather than truncated, and a conversion that only changes signedness at one width still
reinterprets.

`F64` is IEEE-754 double and follows IEEE 754 rather than the integer rules: division by zero is an
infinity or a NaN rather than a trap, a NaN comparison is false, an integer converts to a float by
rounding to nearest with ties to even and a float to an integer by truncation, with a value outside
the integer's range rejected when known and stopped when not. There is no `F32`.

A float literal is written with a point, an exponent, or both, and its type is F64: `1.5`, `1e5` and
`1.5e-3` are one value each. A point needs a digit on both sides, so `1.` is the integer 1 followed by
a `.` rather than a float, and a member selection never has to guess which was meant. A hexadecimal
literal keeps its `e` as a digit, so `0x1e5` is an integer. A digit separator may appear between any
two digits of the mantissa or the exponent, and an exponent needs at least one digit. A float literal
does not adopt another operand's type the way an integer literal does: `1.5` is F64 and stays F64.
`true` and `false` are Bool. `Unit()` is the Unit value.

Comments begin with `--`. `--` followed immediately by a long bracket opens a block comment that ends
at that bracket's own closing form, so it may span lines and its body may contain anything; any other
`--` runs to the end of the line. A line comment is the only newline-sensitive lexical
rule. Operators use longest-token matching, so `!=`, `<<=` and `->` are single tokens.

An item boundary is grammatical, not visual. In a block, `let`, `return`, statement `if`, and `end`
cannot continue an ordinary expression. Adjacent names do not apply functions. A postfix `(` or `{`
CAN continue the preceding expression across a newline; use `;` if separation is intended. A return
of Unit before an expression statement must be written `return;` (the following statement is then
unreachable), not inferred from a line break.

## 2. Bindings and named definitions

```
let x = 42
let flag: Bool = true
let affine(a, b, x: U32) : U32 = a * x + b
```

`let` introduces an immutable lexical binding. An optional annotation checks its value; it is not a
conversion chosen by the backend. Bindings cannot be reassigned. A binding can hold a mutable record
instance, however: binding immutability does not freeze that instance's fields.

A named definition is sugar for binding a word. Parameters are ordered and have immutable bindings.
Adjacent names share the following annotation: `(a, b, x: U32)` declares three U32 parameters. Every
named-definition parameter must have an annotation. The result annotation is optional except where
section 10 requires it. Duplicate parameter names reject.

A named definition may take **keyed** requirements instead, written like a schema's members:

```
let distance { x: U32, y: U32 }: U32 = x * x + y * y
let d = distance { x = 3, y = 4 }
```

Every keyed requirement is annotated, because a key has no position to infer a type from. Supplying
every key invokes the body; supplying fewer returns a specialized word, exactly as ordered partial
supply does, and the supplied values must be static. Keyed requirements have no order, so supplies
may be written in any order, and the word is applied by name. A schema is the special case of a
keyed word whose terminal constructs an instance.

Type requirements are evaluated left-to-right when arguments are supplied. An earlier parameter may
appear in a later requirement:

```
let identity(T: Type, x: T) = x
```

T must be known before checking x's requirement. This is ordinary type demand, not an implicit type
parameter or a new `static` keyword.

Top-level binding names are mutually visible; their initializers are evaluated once, eagerly, during
module initialization in declaration order. A forward reference demands a later initializer early,
and a cycle demanding a value before its initializer completes rejects. Creating a word does not
execute its body, so mutually recursive word definitions need no forward declaration.

Local bindings are visible after their initializer, not throughout the block. A local named word
also sees its own name in its BODY, permitting self recursion; this does not make an arbitrary local
initializer self-referential. Mutually recursive local declarations are not introduced by this syntax.
Shadowing an outer binding is allowed; duplicate declarations in one lexical scope reject. Parameters
and body declarations follow that same rule.

## 3. Application and partial supply

Application uses parentheses, never juxtaposition:

```
let transform = affine(4, 3)
let nineteen = transform(4)
```

Evaluate the callee, then arguments left-to-right. Adjust result lists as in section 6, check the
supplied requirements, append those arguments, THEN test saturation.

- Fewer arguments than remaining requirements: return a specialized word. All supplied arguments
  must be static values, free of runtime captures and mutable storage bindings.
- Exactly the remaining requirements: invoke the word's terminal. Arguments may be static or runtime.
- More than the remaining requirements: reject. Arguments are not implicitly forwarded to a result.
- No arguments with outstanding requirements: return the same word; no terminal executes.
- No arguments with no outstanding requirements: invoke the nullary terminal once.

A signature without an implementation can describe/check a calling requirement but cannot be
invoked to fabricate a result. Fully supplying such a descriptor does not supply its missing code.

Partial supply is static specialization, not an implicit closure allocation. To capture an immutable
runtime value, write a lambda explicitly:

```
let add(a, b: U32) = a + b
let add_runtime(n: U32) = |x: U32| -> add(n, x)
```

Inside a residual function `add(n)` rejects if n is runtime; `add(n, x)` is a valid saturated call.
Capturing a borrowed method in a lambda yields a borrowed lambda, with the escape restrictions of
section 9. It does not make an owning closure by spelling the operation differently.

At a saturated call, known arguments specialize automatically. `affine(4, 3, x)` and `transform(x)`
share the same residual specialization when their other bindings agree. Staticness is a property of
the complete invocation, including receiver/captures. Empty-argument `r.draw()` is not static if r is
runtime storage. Known current contents do not make a mutable record a static argument.

## 4. Anonymous words and signatures

Every lambda uses pipes:

```
|x| -> x + 1
|a, b| -> a ~ b
|x: U32| -> x + 1
|a, b: U32| -> do let t = a * a  return t + b end
|| -> Unit()
```

Bare `x -> ...` is NOT a lambda form: `->` only ever introduces a lambda body. A result is written
with `:`, and a signature's inputs are parenthesized, so a signature is unambiguous even when its
type aliases are lowercase and even inside a lambda's parameter list:

```
let number = U32
let Endo = (number): number
```

Lambda parameters use the same grouping rule as named parameters. Missing annotations require an
expected callable signature, supplied by an annotated binding, a parameter requirement or a result
contract. Every missing parameter type must be determined by that context; arbitrary body-based
parameter inference is not performed. An untyped standalone lambda rejects.

```
let inc: (U32): U32 = |x| -> x + 1
let twice(f: (U32): U32, x: U32) = f(f(x))
let inc_2x = twice(|x| -> x + 1)
```

Expected callable types are passed to lambda arguments as their corresponding requirements become
known. This is checking, not permission to reorder argument effects. In a conditional checked against
a signature, propagate that expectation into both value-producing arms.

`->` introduces a lambda's BODY; it never denotes a result type. A lambda's result is declared by an
annotated binding or by the requirement it is passed to. Typed lambda parameters plus an inferred
result are also valid, and a lambda body may itself be a signature: `|x: U32| -> (U32): U32`.

Signature forms are:

```
(U32): U32                    -- one input, one result
(U32, U32): U32               -- two inputs
(): U32                       -- no inputs
(U32): (U32, U32)             -- two results
(U32): ()                     -- Unit result contract
(U32): ((U32): U32)           -- one callable result
```

A parenthesized comma list before the `:` is the input list; a comma list after it is the result
list. Neither creates tuple values. An empty list denotes no inputs, or one Unit result. A
parenthesized single type is grouping and is equivalent to that type, so `(U32): U32` has one input.

A signature is a calling requirement, not executable code. Checking known code against it verifies
parameter and result requirements without arbitrarily erasing known implementation identity. Unknown
runtime code needs a complete signature and uses the non-retaining callable ABI. A signature alone
is not an assertion that a callable owns an environment.

## 5. Bodies, blocks and conditionals

A word body is an expression or a `do ... end` block:

```
let square(x: U32) = x * x
let square_block(x: U32) = do
  let result = x * x
  return result
end
```

An expression body returns that expression's result vector. A block has no implicit last-expression
result: every reachable function path must return. A bare `return` returns Unit. A declaration or
call statement at the end does not imply a return. Code after a definitely terminating statement in
the same list is rejected as unreachable.

Blocks may contain declarations, field assignments, compound field assignments, call statements,
statement conditionals, deferred actions and returns. A call statement must be saturated; it evaluates
the call and discards its result vector, and a deferred action is a call statement that runs when the
block it is written in is left (section 8.8). Discarding an incomplete word is an error, not a call
for effects. Arbitrary unused arithmetic expressions are not statements. `do ... end` is a body form,
not a standalone value expression or a declaration-scope statement.

Conditionals have two grammatical forms:

```
let chosen = if condition then a else b

if condition then
  r.draw()
else
  r.draw()
  r.draw()
end
```

An expression conditional requires else and has no trailing end. Its arms are expressions, each
producing a result vector. A statement conditional has statement-list arms, optional else, and a
terminating end. After then/else, statement versus expression parsing is determined by which form
was entered; a leading statement-position if is never guessed to be an expression statement.

Conditions must be Bool. A known condition evaluates only the selected arm; the other arm is parsed
and lexically resolved but not semantically evaluated. An unknown condition elaborates both arms once.
Continuing expression arms must agree in source result arity and compatible component types. Identical
known components remain known; differing representable values require runtime result slots. Different
static-only type values cannot be turned into a runtime Type.

Each arm has a child lexical scope. Declarations inside an arm do not escape. An arm that returns
from the enclosing word does not reach the continuation. A missing statement else is an empty
continuing arm. Thus this is complete without any fictitious value from the first arm:

```
let skip(s, n: U32) : U32 = do
  if n == 0 then return s end
  return skip(next32(s), n - 1)
end
```

## 6. Multiple results and adjustment

Multiple results are an ordered result vector, not a tuple value:

```
let divmod(a, b: U32) : (U32, U32) = do
  return a / b, a % b
end

let quotient, remainder = divmod(17, 5)
let q: U32, r: U32 = divmod(17, 5)
```

For ordinary bindings, each name has its OWN optional annotation. `let a, b: U32 = ...` annotates b
only; shared annotations are restricted to parameter lists. Each bound name is fresh and immutable.
This is result-list binding, not recursive destructuring or a pattern language.

Expression evaluation has a result vector. Scalar contexts take its first value: arithmetic,
comparison, condition, callee selection, field base, record-field initializer and a supplied type
requirement. Extra values are discarded AFTER the expression executes. Parenthesizing an ordinary
expression explicitly adjusts it to one result: `(divmod(a, b))` yields only the quotient.

In an argument list, return list or binding initializer list, all expressions except the final one
contribute one result. The final expression contributes its complete vector. Evaluate expressions
left-to-right before adjustment. Named record initializer items each contribute one value and never
expand a result vector across fields.

```
let forward(a, b: U32) = divmod(a, b)        -- forwards both results
let first(a, b: U32) = (divmod(a, b))        -- returns one result
```

Binding lists discard surplus values and fill missing values with Unit. An annotation incompatible
with that Unit rejects. Call argument lists do NOT fill missing parameters: after expansion they
follow partial/saturated application rules. Return vectors must match the enclosing declared or
inferred result contract exactly; they are not padded to satisfy it.

Zero results and a bare return denote one Unit result in Wordlet. Explicit Unit slots in multiple
results remain logical slots even though C erases their payloads. `return Unit(), 3` has arity two.
A callable expression returning multiple results as an expression body forwards all of them.

## 7. Operators and evaluation order

Tightest first:

| Level | Operators | Associativity |
| --- | --- | --- |
| postfix | `f(...)`, `T {...}`, `.name` | left |
| power | `^` | right |
| unary | `-`, `~`, `not` | prefix |
| multiplicative | `*`, `/`, `%` | left |
| additive | `+`, `-` | left |
| shift | `<<`, `>>` | left |
| bitwise and | `&` | left |
| bitwise xor | `~` | left |
| bitwise or | `\|` | left |
| comparison | `==`, `!=`, `<`, `<=`, `>`, `>=` | non-associative |
| logical and | `and` | left |
| logical or | `or` | left |

Pipes in prefix position introduce a lambda; infix pipe is bitwise-or. A lambda parameter annotation
stops at the closing pipe, so `|f: (U32): U32| -> f` reads as one parameter whose type is a signature.
The lambda body extends as a full body/expression to its enclosing delimiter. Signature arrows do
not introduce parameter names or executable bodies.

Power binds tighter than unary on its left: `-x ^ 2` means `-(x ^ 2)`. Unary is allowed on the right
of power, so `x ^ -1` means `x ^ (-1)`. Here -1 is modular U32 negation, not a signed exponent. Two
comparisons cannot chain without explicit grouping; `a < b < c` rejects.

Arithmetic and bitwise operators require one integer type, except that `+`, `-`, `*` and `/` also
apply to F64. As section 1 says, a literal adopts the other operand's type when its value fits,
mixed widths of one signedness widen to the wider one, and mixing signed and unsigned rejects.
Add/subtract/multiply/negate/power wrap at the width the type names.
`0 ^ 0` is 1. Division truncates toward zero, with the remainder taking the dividend's sign; a known
zero divisor rejects and a dynamic one aborts at runtime. A right shift is logical for an unsigned
type and arithmetic for a signed one, so it keeps the sign bit; a shift amount at least the width
yields zero, or the sign fill for an arithmetic right shift. No implicit Bool/integer conversion
exists.

Ordered comparison requires one integer type or F64, and equality requires equal scalar types (one
integer type, Bool, F64 or Unit; Unit equals Unit). A comparison widens its operands to one integer
type the way an arithmetic operation does. Two `String` values compare by content, since a byte
sequence has no identity a program can observe. Record, word, type, slice and callable equality are
not added by the equality tokens.

`and`, `or`, `not` require Bool and produce Bool. There is no truthiness and no operand-valued Lua
and/or behavior. `and` and `or` short-circuit. Other binary operators evaluate operands left-to-right;
all source call and initializer evaluation order is preserved by generated C.

Supported compound field stores are exactly `+=`, `-=`, `*=`, `/=`, `%=`, `^=`, `&=`, `|=`, `~=`,
`<<=`, and `>>=`. Their operand rules are those of the corresponding operation. There is no comparison
assignment, logical assignment, `:=`, increment operator or rebinding assignment.

For `base.field op= rhs`, evaluate the target base/path once, read the old field value once, then
evaluate rhs, compute the operation and store. If rhs mutates that field, the final operation still
uses the earlier snapshot. Plain field assignment evaluates its target once, then rhs, then stores.

## 8. Records, keyed supply and methods

```
let Point = { x: U32, y: U32 }
let p = Point { x = 3, y = 4 }
let old = p.x
p.x = 20
```

A schema literal contains named data requirements and optional methods. A named initializer occurs
only AFTER a word expression, as postfix keyed application. Bare `{x=3}` is not an untyped record
value. Bare `{}` is the empty record schema; `Point {}` is an empty keyed supply. Schema field order
does not determine identity or layout. Duplicate names and reserved-member collisions reject.

Keyed application accepts named supplies, not positional arguments. Unknown names and resupplying a
bound field reject. An incomplete keyed supply produces a specialized schema word and requires all
supplied values to be static. Bound fields are static, readable and non-writable. Saturation constructs
a fresh record with its remaining data fields initialized. Ordinary saturated constructor arguments
that happen to be known do NOT thereby turn those source fields into readonly static fields.

```
let AtX3 = Point { x = 3 }
let p = AtX3 { y = 4 }           -- x is statically bound; y is an instance field
```

Initializer expressions execute in written order even though fields are stored canonically. Methods
are code members, not initializer fields or stored function pointers. Record arguments, assignments
into fields and returns have value-copy semantics; local aliases to an instance retain that instance.

```
let Rng = {
  state: U32,
  draw() : U32 = do
    state = next32(state)
    return state
  end,
}

let draw_once(s: U32) : U32 = do
  let r = Rng { state = s }
  let before = r.state
  r.draw()                      -- saturated call statement; result discarded
  return before
end
```

An immutable binding to r permits writes to r.state; `r = ...` rejects. Bare `state = ...` inside a
method resolves to its receiver field, not a local binding. Ordinary locals/parameters shadow field
names; assigning a shadowing immutable binding rejects rather than falling through to the field.
Explicit `r.state` selection uses r's actual instance.

A method borrows its actual receiver. Selecting it on an instance binds that receiver. Selecting it
on a schema produces an unbound method interface useful for export, but it cannot be called without
an actual receiver. No source `&T` parameter or guessed dynamic caller supplies one.

Nested lexical owners use actual enclosing records and explicit occurrence routes. Copying a child
record alone does not invent its former parent. Source definitions do not acquire mutable parent
pointers. Missing required owner bindings reject.

### 8.1 Sums

A sum type is a finite set of named alternatives, each with its own payload type. It is a keyed
schema read as a tag plus a payload, so it needs no new syntax of its own: the schema's field names
are the alternatives and the field types are their payloads.

```
let Circle = { radius: U32 }
let Rect = { width: U32, height: U32 }
let Shape = OneOf({ circle: Circle, rect: Rect })
```

`OneOf(cases)` takes one keyed schema and produces a type value. Alternative order is canonical, not
written order, so two spellings of the same alternatives are the same type. `OneOf` requires a schema
with at least one named alternative; an empty schema, or a non-schema argument, rejects. The schema
may also be written directly after the word,

```
let Shape = OneOf { circle: Circle, rect: Rect }
```

which is the keyed spelling of `OneOf({ circle: Circle, rect: Rect })`. A word's keyed requirement is
attached with braces, exactly as `Point { x = 3 }` attaches a keyed supply, and the entry separator
decides which: `name: Type` defines, `name = value` supplies.

Member selection on a sum type names a constructor for one alternative:

```
let round = Shape.circle { radius = 3 }
let flat = Shape.rect { width = 4, height = 5 }
```

An alternative whose payload is a record is constructed by keyed supply, checked and stored exactly
like the payload record itself. An alternative whose payload is not a record is applied to one value
positionally, and a `Unit` alternative is applied to nothing (`Opt.none()`). Selecting a name that is
not an alternative of that sum rejects.

Matching is keyed application of a sum value with one handler per alternative. The handlers are
callable values, each receiving that alternative's payload:

```
let area(s: Shape): U32 = s {
  circle = |c: Circle| -> c.radius * c.radius,
  rect = |r: Rect| -> r.width * r.height,
}
```

Every alternative must be handled exactly once; a missing or duplicated alternative rejects. Every
handler must be callable, and every handler must produce the same result type. A value whose
alternative is known selects its handler directly and evaluates no other handler, so an unreachable
handler body is not compiled for that occurrence. A value whose alternative is only known at run time
becomes a tag test per alternative with the payload projected inside the matching arm.

A sum value is immutable like a record; its alternatives have no selectable members. A payload is
reached by matching, not by naming an alternative in a member select. Sum values copy by value on
argument passing, assignment and return.

Recursive sums are not expressible without an indirection boundary: an alternative's payload type
must already be defined, so a sum cannot mention itself by value. Section 8.2 supplies that boundary.

### 8.2 References and recursive types

A reference names a place instead of copying it. It is one of the three indirection boundaries that
make a recursive type finite -- `Ptr` (section 8.5) and `Slice` (section 8.4) are the others -- and it
is what lets a sum mention
itself:

```
let Node = { value: U32, next: Link }
let Link = OneOf({ none: Unit, some: Ref(Node) })
```

`Ref` is an ordinary word, so it needs no new syntax: applied to a type value it produces a type,
and applied to a place it produces a reference to that place.

```
let Counter = { value: U32 }
let c = Counter { value = 1 }
let r = Ref(c)                 -- r : Ref(Counter)
r.value = 20                   -- writes c.value: selection through a reference is a place route
let again = Ref(c)             -- a second reference to the same instance
```

A reference is an ordinary value: it may be a parameter, a result, a field or a local binding, and
passing or returning one passes the reference, not the instance. A function may therefore take
`Ref(T)` and write through it, and a reference to module storage may be returned from a call and
followed there. A host that holds such a pointer may pass it directly.

`Ref(T)` is not a copy of `T`. Reading or writing through a reference reaches the referenced
instance, exactly as selecting that instance directly would, and two references to one instance
observe each other's writes. A reference has stable identity under copying: copying a record that
holds a reference copies the reference, not the referenced instance. Assigning through a reference
to a field of a *binding* still rejects: `r = ...` is not a store, only a place beneath `r` is.

`Ref` never means ownership, uniqueness, move or automatic destruction. A reference does not keep
its target alive, and it is not the mechanism by which a record owns a child.

#### What a reference may name

A reference may only name a target that provably outlives every use of the reference. Exactly two
targets qualify:

1. **an enclosing owner.** The referenced place is a lexical owner that encloses the reference and
   outlives it in the same activation. This is the same actual-owner route that a captured receiver
   already uses.
2. **module-level storage.** A binding declared at file scope outlives every activation, so a
   reference to it may be copied, stored and returned freely.

Anything else rejects (`ref-target`): a local that does not enclose the reference, a temporary, a
field of a record that is about to be copied, and a place that has already been replaced. A reference
is not itself a place to reference again, so `Ref(Ref(x))` rejects rather than collapsing two
indirections into one.

A record that holds a reference to an enclosing owner is itself tied to that activation: it may be
used, copied and passed within the activation, but returning it, storing it in module storage or
capturing it in an escaping closure rejects (`ref-escape`). A record that holds only references to
module storage has no such restriction, because those targets outlive every activation.

```
let Counter = { value: U32 }
let shared = Counter { value = 0 }              -- module storage

let Node = { value: U32, next: Ref(Counter) }
let local(x: U32): U32 = do
  let n = Node { value = x, next = Ref(shared) }
  return n.next.value                            -- fine: the target is module storage
end

let bad(x: U32): Node = do
  let c = Counter { value = x }
  return Node { value = x, next = Ref(c) }        -- rejects: c dies with this activation
end
```

A recursive type definition must be a file-scope binding. File-scope names are mutually visible and
demanded lazily, which is what lets two definitions mention each other, but a local binding is
declared in order and its initializer cannot see its own name, so a local definition that names
itself rejects like any other forward reference.

#### Recursive type identity

A type whose definition needs itself is a **recursive type**. The first demand for such a
definition reserves its cell; a demand that arrives while the cell is still being computed yields an
indirection to that cell rather than forcing its layout. The cell is sealed with the finished
definition and the result must not change afterwards.

```
let Bad = { child: Bad }        -- rejects: by-value containment has no finite layout
let Good = { child: Ref(Good) } -- accepted: the layout cycle crosses the reference boundary
```

A by-value cycle rejects (`type-cycle`) even when it passes through several definitions. A cycle
that crosses an indirection, a reference or a raw pointer, is finite: either has a representation
whose size does not depend on
its target. Type equality is structural, except that a recursive definition compares by its reserved
identity, so two spellings of one recursive knot are one type and one layout.

#### Validation

Required reference tests include:

- reference construction from each legal target, selection and store through a reference, aliasing
  between two references, and copying a reference by value;
- both lifetime rules and both rejections (`ref-target`, `ref-escape`);
- a finite recursive list built over module storage: construction, traversal, and a mutation seen
  through a stored reference;
- by-value cycles across one and several definitions (`type-cycle`), and a cycle broken only by a
  reference being accepted with a finite layout.

### 8.3 Arrays

An array is a fixed-length sequence of one element type. The type is `Array(T, N)`, an ordinary word
applied to an element type and a length, and a literal is written with brackets:

```
let xs = [10, 20, 30]
let ys: Array(U32, 3) = [10, 20, 30]
let first = xs[0]
let pick = |i: U32| -> xs[i]
xs[1] = 99
xs[0] += 5
```

The length is part of the type, so it is never inferred from a later assignment and a literal is
checked against it. A literal takes its element type from its elements, or from an annotation, which
is what an empty literal needs: `[]` with no element has nothing to infer from and rejects
(`type-required`). A literal whose length does not match, whose elements do not share one type, or an
`Array` whose length is not a positive literal rejects (`array-length`, `type-mismatch`).

Indexing is `a[i]` for a `U32` `i`. A known index outside the array rejects while compiling
(`index-range`); any other index is checked at run time and a failure aborts, exactly as a run-time
zero divisor does. An element is assignable and every compound store form applies to it. Elements are
values: reading one copies it, and an array is copied by value when it is passed, returned or assigned
into a field.

An array is a value with an identity, like a record instance. A local binding to one is an alias, so a
write through either name is visible through both; passing an array to a word, returning it or storing
it into a field copies it. A record field or a parameter may be of array type, and an array element may
itself be an array, so `g[r][c]` indexes a grid.

### 8.4 Slices and strings

A slice is a runtime-length view of storage someone else owns. It is the one array-like type whose
length is not part of the type, which is what lets one word accept a sequence of any extent:

```
let sum_from(xs: Slice(U32), i: U32, total: U32) : U32 = do
  if i == 0 then return total end
  return sum_from(xs, i - 1, total + xs[i - 1])
end

let sum(xs: Slice(U32)) : U32 = sum_from(xs, xs.length, 0)
```

`Slice(T)` is an ordinary word, like `Ref`: applied to a type it produces a type, and applied to an
array it produces a view of that array.

```
let xs = [10, 20, 30]
let view = Slice(xs)          -- Slice(U32); view.length is three
let middle = view[1]          -- a run-time-checked element read
```

A view names a place, so section 8.2's lifetime rule applies to it unchanged. A view of module storage
may be copied, stored and returned; a view of a local, or of storage that belongs to an enclosing
activation, is tied to that activation and rejects when it escapes (`borrow-escape`). A view borrows
storage; it never owns it, and it does not keep its target alive.

A view is read-only. `xs[i] = v` writes the array; `view[i] = v` rejects (`not-a-place`), because the
view does not own the storage it names, and the bytes of a string literal are not writable.

Indexing is `view[i]` for a `U32` `i`. A known index outside the known length rejects while compiling
(`index-range`); any other index is checked when it runs and a failure aborts, exactly as a run-time
array index does. Reading an element copies it.


A **string** is a slice of bytes: `String` is `Slice(U8)`. Text and bytes are therefore one mechanism
rather than two, and a string has a runtime length like any other view. Its bytes are bytes, not
characters: the source text is already the encoding, so a multi-byte character needs no escape and no
decoding. `"\xff"[0]` is the byte 255.

```
let greeting = "hello"
let count = greeting.length      -- 5
let second = U32(greeting[1])    -- 101
let same = "ab" == "ab"          -- true
```

A literal is written with double quotes. The escapes are `\\`, `\"`, `\n`, `\r`, `\t`, `\0` and `\xHH`,
which stands for one byte by its two hexadecimal digits. A raw newline inside a literal rejects, as
does an unterminated literal or an unknown escape (`lex-string`). A literal's bytes live in read-only
storage for the life of the program, so a literal is module storage: it may be copied, returned, stored
and compared freely, and two literals with the same bytes are one buffer.

A **byte literal** is one byte written readably: `'a'` is the byte 97, and it takes the same escapes
a string does, so `'\n'` is 10 and `'\x41'` is 65. It is a numeric literal, not a one-byte string, so
it adapts to the width it is used at and reports `U32` where no other operand decides. A byte literal
that is not exactly one byte rejects (`lex-string`): a multi-byte character is text, so it belongs in
a string.

A **long string** is written `[=[ ... ]=]` with any number of `=` signs, and the same number closes
it. It is raw (no escapes at all), it may span lines, and one newline immediately after the opening
bracket is dropped so a body can begin on the line below it. Because the level is chosen by the
writer, a body may contain any lower level's closing form. A long string needs at least one `=`: `[[`
is already an array whose first element is an array, and that must not become ambiguous.

Equality on `String` compares content rather than identity, and costs one length test before any byte
comparison. Ordering is not offered for `String`, and equality on any other slice type rejects: two
views may name overlapping storage, so identity is not observable and element-wise equality is not
offered by `==`.

No slice operation allocates, grows, frees or copies storage, and no string operation builds a new
string. Building a byte sequence writes into storage the program already has, which is what keeps a
view a view.

A slice is an indirection boundary, so a type may mention itself through one: `let Node = { value:
U32, rest: Slice(Node) }` is finite for the same reason a pointer to itself is, because a view's own
size does not depend on its element.

### 8.5 Raw pointers

`Ptr(T)` is an address the compiler does not track. It is deliberately a different type from `Ref(T)`:
a reference keeps the guarantee of section 8.2, that its target outlives every use of it, and an
address that arrives from a host function cannot make that promise. Widening `Ref` to carry both would
turn a checked borrow into a comment, so the two are separate types and a signature says which one it
means.

A pointer names no lifetime, so none of section 8.2's rules apply to it. It may be null, it may be
stored in module storage, it may be captured, returned, copied and compared, and it may outlive the
storage it points at. That is the point of the type: this is the part of the language where the
programmer is responsible, and the compiler says so by offering no rule to break.

```
extern let host_alloc(bytes: U32) : Ptr(U8)
extern let host_free(p: Ptr(U8)) : Unit

let bytes(n: U32) : Ptr(U8) = host_alloc(n * 4)
```

`p[i]` is the element at index `i` of `p`, for a `U32` `i`, and it has no bounds check: an unchecked
pointer does not carry a length. The element is assignable and every compound store form applies to
it, exactly as an array's element is. For `Ptr(R)` whose `R` is a record, `p.field` selects a field and
a store through it writes that field, on the same route a reference uses.

A pointer is built in one of two ways. A foreign word may return one, and `Ptr(place)` makes one from a
place the program already has:

```
let xs = [1, 2, 3]
let p = Ptr(xs[0])          -- Ptr(U32); the lifetime is written off here, deliberately
```

`Ptr(place)` is the only place a lifetime is dropped, so it is the place to look for one. There is no
other conversion in either direction: `Ref(p)` rejects, because an unchecked address must not become a
checked borrow. Equality on two pointers of one element type compares addresses, and `Null(T)` is the
null `Ptr(T)`.

```
let empty : Ptr(U8) = Null(U8)
let missing = bytes(4) == empty
```

Ordering, pointer arithmetic and any conversion between a pointer and an integer are not offered.
A pointer is an indirection boundary, so it is one of the ways a recursive type can be finite: `let
Node = { value: U32, next: Ptr(Node) }` has the layout of a struct that holds a pointer to itself, and
a cycle that crosses only a `Ptr` is accepted for the same reason one that crosses a `Ref` is. A
by-value cycle that crosses none of them still rejects (`type-cycle`).

`p[i]` is the only arithmetic a pointer has, so one thing has one spelling. A pointer is not a
`Slice`: a slice carries a length and a pointer does not.

### 8.6 Foreign declarations

A host function is declared with `extern`. It has no body, because its implementation is not written
in this language, so its result and every one of its requirements are written down:

```
extern let host_add(a: U32, b: U32) : U32
extern let host_scale(a: U32) : U32
```

The C symbol is exactly the name that is written. There is no alias and no `pub`, and the host
provides that symbol with that signature and C linkage. A requirement or a result must be a type this
language already has a C representation for, which is the same requirement an exported function's
signature meets, so a foreign declaration cannot invent a layout and "arbitrary foreign layouts" stays
excluded.

A foreign call is an effect the compiler cannot see into. It is never folded, so a constant argument
does not make it a compile-time value, and it exists only where there is code to emit: the reference
interpreter has no binding to call and rejects it (`foreign-effect`). A `Unit` result is erased like
any other, so a call to a `Unit` foreign word is a statement. There is no body to specialize, so a
partial supply rejects rather than producing a partial word.

### 8.7 Scoped resources

A callable requirement may be a word, so a resource can be acquired and released around a body without
an ownership system, a destructor or a keyword. This is the shape, not a built-in:

```
let with_region(R: Type, bytes: U32, body: (Ptr(U8)): R) : R = do
  let region = host_alloc(bytes)
  let result = body(region)
  host_free(region)
  return result
end

let sum() : U32 = with_region(U32, 8, |p: Ptr(U8)| -> do
  p[0] = 7
  p[1] = 35
  return U32(p[0]) + U32(p[1])
end)
```

When the body is known code it is specialized, which is what keeps this cheap: the body's code is
emitted inside a per-invocation copy of the combinator, the call site is a direct call to that copy,
and no function pointer is involved. When the combinator's own body is foldable as well -- when it
has no effect of its own -- the whole call folds away and nothing at all is left, which is the case
measured for a body of pure arithmetic. So a known body costs at most one direct call; what it never
costs is a dynamic one. When the body arrives as a run-time view the combinator is an indirect call
and the release still runs. A `return` inside the body returns from the *body*, not from the
combinator, so the release runs on every normal path.

What this does not do is enforce anything. A pointer into the region may be returned, stored in module
storage or captured by a closure that outlives it, and the compiler accepts that, because a `Ptr`
carries no lifetime to check and an abort does not unwind, so a release can be skipped. `with_region`
cleans up; it does not prevent misuse. This is the trade the design accepts, and it is the reason a
region's memory arrives as `Ptr` and never as `Ref`: a program that needs the guarantee writes its own
region type and keeps the pointer inside it.

### 8.8 Deferred actions

`defer` attaches an action to the end of the block it appears in, so a release does not depend on
remembering it at every way out:

```
let sum() : U32 = do
  let p = host_alloc(8)
  defer host_free(p)
  p[0] = 7
  p[1] = 35
  return U32(p[0]) + U32(p[1])
end
```

The action is a call statement, and it is written where the bindings it uses are in scope. Its callee
and arguments are evaluated where the `defer` is written, so the action runs with the values the
program had at that point and not with whatever the names mean later: a mutable field read at the
`defer` is a snapshot, exactly as every other read is. The call itself happens when control leaves the
block, after the returned expression has been evaluated and before the value leaves, and several
deferred actions in one block run in reverse order of their `defer` statements.

Every way out of the block runs them: falling off the end, a `return`, the end of a statement
conditional's arm inside it, and a tail self-call. A block with a deferred action therefore does not
turn a tail self-call into a loop, because the action has to run after the call returns and before the
value leaves, which is not the order a back edge would give.

`defer` is a statement form and not a type, so it tracks nothing: it does not prevent the resource
from being used after the action runs, it does not follow a copy of anything, and it does not run at
all when an abort ends the process. It is section 8.7's shape, written where the resource is acquired.
Ownership, moves and automatic destruction remain excluded; a deferred action is a release point the
program placed, not one the compiler inferred.

## 9. Callables, captures and ownership

Known executable arguments retain code identity and specialize. Unknown runtime implementations
are checked against a complete calling signature and use a non-retaining callable view. There is
no `dyn` keyword; binding time and representation requirements decide which is needed.

A conditional whose two arms are callables of one signature but different code joins them into a
tagged callable: the tag names the code and the payload is that code's environment. A call on such a
value tests the tag and then runs that arm's own body, so the call is still direct and no function
pointer is involved. Both arms must be callable the same way; a word arm also needs declared result
types, because a tagged call site has no annotation to fall back on, and a partially applied arm
needs static arguments. An arm that borrows storage has no representation in a tagged value, because
the value holds its environments by value.

A tagged callable owns its environments like any other owned callable, so it may be returned or
stored. It cannot be erased into a bare signature: a view does not retain the environment that
carries the tag, so that conversion rejects (`callable-erase`) rather than dangling. Erasing a
callable whose arm is already known is ordinary erasure of that one callable.

Lambda captures follow lexical bindings. A captured scalar/read snapshot is an immutable value.
Capturing a mutable record instance or a method retains its actual place; copying its binding does
not secretly copy its state. Owned value captures form a by-value environment. A closure containing
any receiver/place borrow or another borrowed callable is borrowed.

Owned closures may return and copy. A closure with no captures is pure code: it owns nothing, so it
may also return or be stored, and it crosses a boundary as an invocation pointer with a null
environment rather than an environment record. Borrowed closures and method values can be invoked locally or
passed to non-retaining callable parameters, where the parameter takes a view whose adapter holds the
borrowed place (a method value passes its receiver); they cannot return or be stored in ordinary record fields, including through nested
aggregates/results. Returning the stateful record and selecting its methods afterwards
is valid. An opaque signature does not prove ownership; its runtime symbols are conservatively borrowed.

A result annotation that is a signature checks callable shape; it is not permission to erase an owned
environment into a dangling pointer. A concrete owned result also needs a known code/environment ABI.
If a recursive result contract cannot establish that ABI, compilation rejects the unresolved recursive
representation rather than pretending the signature alone specifies ownership or environment size.

## 10. Results, recursion and generics

Result annotations constrain every reachable result vector. Without an annotation, acyclic bodies
infer their result types and any common static components. A known condition need not evaluate an
unselected branch, but all returning arms of an unknown condition must agree as specified above.

Every word in a residual recursive strongly connected component requires a complete result contract,
from its definition/binding annotation or the module's results table. All applicable contracts must
agree. This intentionally replaces the earlier inference-only-when-ungrounded rule.

Static recursive evaluation can run without a residual result contract, subject to interpreter depth
and work bounds. A source recursive function whose static arguments change may produce distinct keys;
that is bounded specialization, not automatically a same-key tail loop.

Generics are ordinary words with Type parameters:

```
let identity(T: Type, x: T) = x
let twice(T: Type, f: (T): T, x: T) = f(f(x))
let identity_u32 = identity(U32)
```

There is no implicit generic parameter inference. A runtime value cannot supply Type. Static types
are compile-time values and may be returned by private helpers when all their returning paths agree;
they cannot occupy an external C value slot. Public callable signatures must have a closed runtime ABI.

## 11. Modules and export configuration

A Wordlet source file uses the `.let` extension and contains top-level let declarations followed by
exactly one final module export declaration:

A file that defines a top-level word `main` may instead omit the export configuration; `main` is
then the only export. That is what lets a `.let` file be written as a program rather than as a
module, and a host runs it by calling `main`.

```
return {
  types = { Rng },
  functions = { next32, seed, skip },
  results = { [Endo] = U32 },
}
```

This final construct is MODULE CONFIGURATION, not a general source record expression or a runtime
return. Its brace/list/bracket forms are parsed by a separate configuration grammar. It is never
stored in a Wordlet record or emitted as a C value. There are no strings, arrays or general indexing
operators introduced into source expressions by this notation.

Allowed sections are types, functions and results, each optional and present at most once. Unknown
sections reject. List entries in types/functions are names, or named aliases:

```
return {
  functions = { next32, d6 = roll(6) },
  types = { Rng, Counter = SomeCounter },
  results = { [helper] = (U32, Bool) },
}
```

A bare identifier exports under its own spelling. `alias = expression` gives an explicit public name;
its expression must yield a known type or executable selection appropriate to the section. Duplicate
public names within a section reject. Qualified selections require aliases, such as `draw = Rng.draw`.
Method exports expose their receiver as the C entry's receiver parameter, not as an invented source
argument. A view bound to mutable module-evaluation storage cannot be exported as implicit C global
state.

Results entries use `[word-or-signature-expression] = result-spec`. A result-spec is one type, an
ordered parenthesized type list, or () for Unit. Known code contracts and structural signature contracts
are distinct: a signature entry constrains that calling interface; a code entry constrains that word
specialization and compiler-derived refinements. Explicitly partial-specialized words have their own
contracts; implementation must check all applicable contracts and reject contradictions, never silently
override an annotation. No static-result assertion syntax is introduced by this table.

Module initialization is compile-time interpreter execution over concrete values, so an initializer
may read module storage and build temporary records. A module-level mutable instance that runtime
code refers to also gets named file-scope storage, and the artifact emits an exported
`void wordlet_init(void)` that assigns each such object its start value; the host calls it explicitly.
An initializer may also write module storage, so a mutable instance's start value can depend on the
initialization that preceded it.
Returned exported code cannot retain a mutable module instance without a specified runtime storage
interface. Immutable scalar snapshots and static definitions are valid captured metadata. Top-level
initializers are evaluated once, eagerly, in declaration order; a forward reference demands a later
initializer early. Dependency cycles reject.

A module may use another with `use <dotted name>` at the top of the file. The name is a path next to
the importing file with dots as separators and `.let` implied, so `use util.helper` reads
`util/helper.let`. The last segment is the namespace the module's exports are reached through:

```
use util
let twice(n: U32): U32 = util.helper(n)
let origin(): util.Point = util.Point { x = 1, y = 2 }
```

What a module offers is exactly its export list, so `util.helper` and `util.Point` work only if the
used file exports them; any other name stays private to that file. A used module's own imports are
resolved first, a module is loaded once however many files use it, and a cycle rejects
(`import-cycle`). Modules compiled together share one translation unit and one initialiser, so
file-scope mutable storage in a used module is initialised by the same host call. Only a file can use
an import, because a source string has no directory to resolve against.

There is no `pub` syntax in this version. There is no traps section: known zero division
rejects, dynamic zero division aborts. Configurable failure handling and module imports need separate
language decisions.

## 12. Grammar outline

This grammar fixes the previously overlapping forms. Expression productions use the precedence table
in section 7. Semantic arity/staticness/type checks are not disguised as parser decisions.

```
module          := top-let* export-config EOF
local-let       := named-definition | keyed-definition | value-binding | foreign-declaration
named-definition:= 'let' Name parameters result-annotation? '=' body
keyed-definition:= 'let' Name keyed-parameters result-annotation? '=' body
keyed-parameters:= '{' (Name ':' type-expression) (',' Name ':' type-expression)* ','? '}'
-- A host function: no body, so the result is required rather than optional.
foreign-declaration := 'extern' 'let' Name parameters ':' result-spec
value-binding   := 'let' binder (',' binder)* '=' expression-list
binder          := Name (':' type-expression)?
parameters      := '(' parameter-groups? ')'
parameter-group := Name (',' Name)* ':' type-expression
result-annotation := ':' result-spec
result-spec     := type-expression | '(' type-list? ')'
body            := expression | 'do' statement* 'end'
statement       := local-let | field-store | call-statement | return-statement | defer-statement
                 | 'if' expression 'then' statement* ('else' statement*)? 'end'
return-statement:= 'return' expression-list?
defer-statement := 'defer' call-statement
expression-list := expression (',' expression)*
lambda          := '|' lambda-parameters? '|' '->' body
lambda-parameters := parameter groups, with annotations optionally supplied by context
postfix         := atom (arguments | initializer | '.' Name)*
string-literal  := '"' (escape | byte-except-quote-or-newline)* '"'
float-literal   := digits ('.' digits)? exponent? | digits '.' digits exponent?
exponent        := ('e' | 'E') ('+' | '-')? digits
byte-literal    := "'" (escape | byte-except-quote-or-newline) "'"
long-bracket    := '[' '='+ '[' .* ']' '='+ ']'   (same number of '=' on each side)
long-comment    := '--' '[' '='* '[' .* ']' '='* ']'
arguments       := '(' expression-list? ')'
initializer     := '{' (Name '=' expression) (',' Name '=' expression)* ','? '}' | '{' '}'
schema          := '{' schema-members? '}'
schema-member   := Name ':' type-expression | Name parameters result-annotation? '=' body
if-expression   := 'if' expression 'then' expression 'else' expression
signature       := '(' type-list? ')' ':' result-spec
```

Top-let has local-let's syntax but module visibility rules. Optional semicolons delimit complete
items. Delimited comma lists permit a trailing comma; empty parameter/argument/lambda lists are valid.
Parameter groups end after an annotation; a following comma begins the next group. For instance,
`(a, b: U32, c: Bool)` is two groups. In a binding list, annotations belong to individual binders.

A parenthesized comma sequence is legal only as a signature side/result-spec, never as a general
expression. Parser lookahead over balanced parentheses can recognize an input type list followed by
an arrow; scalar grouping otherwise adjusts its expression to one value. Pipe lambdas remove the need
to guess whether a name before an arrow binds a variable or denotes a type.

Type expressions use expression syntax but must evaluate to a type/calling requirement. There is no
separate capitalization rule or implicit conversion of a value into its type. Their surrounding
colon, arrow or list delimiter determines where they end. A result-spec's comma list is distinct
from a single signature-valued result, e.g. `: ((U32): U32)`.

`if a then if b then x else y else z` associates each else with its structurally pending expression
conditional. Statement conditionals have explicit end tokens and cannot consume an expression's else
by switching grammar forms. Semicolons are required to prevent any otherwise valid postfix continuation
across an intended item boundary. Full grammar/parser tests must cover these boundary cases.

## 13. Worked example

```
let xorshift(a, b, c, s: U32) : U32 = do
  let s1 = s ~ (s << a)
  let s2 = s1 ~ (s1 >> b)
  return s2 ~ (s2 << c)
end

let next32 = xorshift(13, 17, 5)
let seed(s: U32) = if s == 0 then 2463534242 else s

let skip(s, n: U32) : U32 = do
  if n == 0 then return s end
  return skip(next32(s), n - 1)
end

let step(s: U32) : (U32, U32) = do
  let t = next32(s)
  return t, t
end

let roll(bound, s: U32) : (U32, U32) = do
  let t = next32(s)
  return t, t % bound + 1
end

let d6 = roll(6)
let d20 = roll(20)

let Rng = {
  state: U32,
  draw() : U32 = do
    state = next32(state)
    return state
  end,
}

let roll_then_step(s: U32) : (U32, U32) = do
  let next, face = d6(s)
  return next32(next), face
end

return {
  types = { Rng },
  functions = { seed, next32, skip, step, roll, d6, d20, roll_then_step },
}
```

## 14. Explicit exclusions and validation

No juxtaposition, layout blocks, implicit block returns, bare-name lambdas, mutable lexical bindings,
general borrow parameters, reference arithmetic, null or dangling references, ownership through a
reference, residual partial application, general tuple values, sparse or growing arrays or a
zero-length array, record-value literals without a
schema, non-exhaustive or recursive pattern matching, implicit type parameters, arbitrary foreign
layouts, `pub`, selective or re-exporting imports and configurable traps are implied by this syntax. A reference is a checked
borrow of a target that outlives it, not a pointer type a program may fabricate. A `Ptr` is the type
that may be null or outlive its target, and it is not a `Ref`; ownership, uniqueness, moves and
automatic destruction are not offered either, so a scoped resource is released by a word that takes a
body (section 8.7) rather than by a destructor.

A slice is a view, not a container. No operation allocates, grows, frees or copies storage, so a
zero-length *type* still rejects even though a runtime length of zero is an ordinary empty view.

Required syntax/semantic tests include:

- whitespace/one-line equivalence, explicit separators, maximal tokens and comments;
- pipe lambdas versus lowercase type aliases/signatures; grouped and nested signature arrows;
- shared parameter annotations versus per-binder annotations; contextual lambda typing;
- static partial supply, residual saturated calls, overapplication and nullary calls;
- multiple-result forwarding/grouping, Unit fill, exact return contracts and result annotations;
- expression/statement conditionals, early returns, short circuit and child lexical scopes;
- immutable bindings versus record stores; compound target/RHS evaluation order;
- sum construction by supply and by positional application, exhaustive matching, known versus
  runtime tags, erased `Unit` alternatives and payload type mismatches;
- keyed partial supply versus mutable fields initialized by a saturated constructor;
- owned scalar captures, borrowed receiver captures and invalid escapes;
- lazy mutually visible module definitions, initializer cycles and exported runtime ABI demands;
- recursive contract requirements and conflicting annotation/configuration contracts;
- configuration forms rejected in runtime expressions and unknown module sections rejected.

This specifies the language choices; it does not replace executable parser, evaluator and C differential
tests. `architecture.md` defines the implementation obligations supporting them.
]==]
