-- luajit tools/bundle.lua [manifest.lua [output.lua]]
-- Explicit manifests avoid pretending that regexp require discovery parses Lua.
local function dirname(path) return path:match("^(.*[/])") or "./" end
local script = debug.getinfo(1, "S").source:sub(2)
local manifest_path = arg[1] or (dirname(script) .. "../bundle-manifest.lua")
local root = dirname(manifest_path)
local function plain(v) return type(v) == "table" and getmetatable(v) == nil end
local function fail(message) error("bundle: " .. message, 0) end
local function module_name(name)
    if type(name) ~= "string" or not name:match("^[%a_][%w_%.]*$") or
        name:find("..", 1, true) or name:sub(-1) == "." then return false end
    for part in name:gmatch("[^.]+") do if not part:match("^[%a_][%w_]*$") then return false end end
    return true
end
local function relative(path)
    if type(path) ~= "string" or path == "" or path:sub(1, 1) == "/" or path:find("\\", 1, true) or path:find("%z") then return false end
    for part in path:gmatch("[^/]+") do if part == ".." then return false end end
    return true
end
local function read(path)
    local f, err = io.open(path, "rb"); if not f then fail(tostring(err)) end
    local text, why = f:read("*a"); local ok, close_err = f:close()
    if not text or not ok then fail(tostring(why or close_err)) end
    return text
end
local function build()
    local chunk, err = loadfile(manifest_path)
    if not chunk then fail(tostring(err)) end
    local spec = chunk()
    if not plain(spec) or not plain(spec.modules) then fail("manifest needs a plain modules map") end
    for key in pairs(spec) do
        if key ~= "modules" and key ~= "entry" and key ~= "cli" and key ~= "external" and key ~= "output" and key ~= "licenses" and key ~= "syntax" then fail("unknown manifest field: " .. tostring(key)) end
    end
    local names, sources, external = {}, {}, {}
    for name, path in pairs(spec.modules) do
        if not module_name(name) or not relative(path) then fail("invalid module name or relative path: " .. tostring(name)) end
        local text = read(root .. path)
        text = text:gsub("^#![^\n]*", "-- bundled script header")
        local syntax, why = loadstring(text, "@" .. path)
        if not syntax then fail(tostring(why)) end
        names[#names + 1], sources[name] = name, text
    end
    table.sort(names)
    if not module_name(spec.entry) or not sources[spec.entry] then fail("entry must name a bundled module") end
    if spec.cli ~= nil and (not module_name(spec.cli) or not sources[spec.cli]) then fail("cli must name a bundled module") end
    local host = spec.external or {}
    if not plain(host) then fail("external must be a dense list") end
    local count = 0
    for index in pairs(host) do
        if type(index) ~= "number" or index < 1 or index % 1 ~= 0 then fail("external must be a dense list") end
        count = count + 1
    end
    for i = 1, count do
        local name = host[i]
        if not module_name(name) or sources[name] or external[name] then fail("invalid, duplicate or bundled external module") end
        external[name] = true
    end
    local output = arg[2]
    if not output then
        if not relative(spec.output) then fail("output must be a relative manifest path") end
        output = root .. spec.output
    end
    if output:find("%z") then fail("invalid output path") end
    local out = {}
    local function emit(s) out[#out + 1] = s end
    emit("-- Generated by tools/bundle.lua; do not edit.")
    -- The language reference leads the file so the single-file distribution is readable without the
    -- source tree. It is the same syntax.md that tools/embed.lua turns into wordlet.docs.syntax, shown
    -- here as comments rather than an escaped runtime string. Like the license notices it is not code.
    if spec.syntax ~= nil then
        if not relative(spec.syntax) then fail("syntax must be a relative manifest path") end
        emit("--")
        emit("-- Wordlet syntax and semantic contract, bundled from " .. spec.syntax .. ":")
        for line in (read(root .. spec.syntax):gsub("\r\n", "\n"):gsub("\r", "\n") .. "\n"):gmatch("([^\n]*)\n") do
            emit("-- " .. line)
        end
    end
    local licenses = spec.licenses or {}
    if not plain(licenses) then fail("licenses must be a dense list of relative paths") end
    local license_count = 0
    for index in pairs(licenses) do
        if type(index) ~= "number" or index < 1 or index % 1 ~= 0 then fail("licenses must be a dense list") end
        license_count = license_count + 1
    end
    for i = 1, license_count do
        local path = licenses[i]
        if not relative(path) then fail("invalid license path") end
        emit("-- License notice " .. i .. ":")
        for line in (read(root .. path):gsub("\r\n", "\n"):gsub("\r", "\n") .. "\n"):gmatch("([^\n]*)\n") do
            emit("-- " .. line)
        end
    end
    emit("local host_require, host_package = require, package")
    emit("local factories, loaded, loading, external = {}, {}, {}, {}")
    local ext_names = {}; for name in pairs(external) do ext_names[#ext_names + 1] = name end
    table.sort(ext_names)
    for _, name in ipairs(ext_names) do emit(("external[%q] = true"):format(name)) end
    emit("local private_package = setmetatable({loaded = loaded}, {__index = host_package})")
    emit("local function require(name)")
    emit("    if loaded[name] then return loaded[name] end")
    emit("    local factory = factories[name]")
    emit("    if not factory then")
    emit("        if external[name] then return host_require(name) end")
    emit("        error('unlisted bundled dependency: ' .. tostring(name), 0)")
    emit("    end")
    emit("    if loading[name] then error('cyclic bundled require: ' .. name, 0) end")
    emit("    loading[name] = true")
    emit("    local ok, value = pcall(factory, require, private_package, name)")
    emit("    loading[name] = nil")
    emit("    if not ok then loaded[name] = nil; error(value, 0) end")
    emit("    if value == nil then value = loaded[name] end")
    emit("    if value == nil then value = true end")
    emit("    loaded[name] = value")
    emit("    return value")
    emit("end")
    for _, name in ipairs(names) do
        emit(("factories[%q] = function(require, package, ...)"):format(name))
        emit(sources[name]); emit("end")
    end
    emit(("local api = require(%q)"):format(spec.entry))
    if spec.cli then
        emit("local source = debug.getinfo(1, 'S').source:sub(2)")
        emit("if arg and arg[0] == source then")
        emit(("    os.exit(require(%q)(api, arg) or 0)"):format(spec.cli))
        emit("end")
    end
    emit("return api")
    local text = table.concat(out, "\n") .. "\n"
    local valid, why = loadstring(text, "@bundle")
    if not valid then fail(tostring(why)) end
    local directory = dirname(output)
    local quoted = "'" .. directory:gsub("'", "'\\''") .. "'"
    local status = os.execute("mkdir -p -- " .. quoted)
    if status ~= 0 and status ~= true then fail("cannot create output directory") end
    local f, open_err = io.open(output, "wb"); if not f then fail(tostring(open_err)) end
    local ok, write_err = f:write(text); local closed, close_err = f:close()
    if not ok or not closed then fail(tostring(write_err or close_err)) end
    io.stdout:write(("wrote %s: %d modules, %d bytes\n"):format(output, #names, #text))
end
local ok, err = pcall(build)
if not ok then io.stderr:write(tostring(err), "\n"); os.exit(1) end
