-- Generate Lua modules that return the .asdl schema text, so the bundled compiler needs no data files.
-- luajit tools/embed.lua [--check]
local function dirname(path) return path:match("^(.*[/])") or "./" end
local here = dirname(debug.getinfo(1, "S").source:sub(2))
local root = here .. "../"

local function read(path)
    local f = assert(io.open(path, "rb")); local s = assert(f:read("*a")); assert(f:close()); return s
end

-- Choose a long-bracket level absent from the text.
local function quote(text)
    for level = 0, 12 do
        local eq = string.rep("=", level)
        local open, close = "[" .. eq .. "[", "]" .. eq .. "]"
        if not text:find(close, 1, true) then return open .. text .. close end
    end
    error("embed: schema text defeats every long-bracket level")
end

local function module_for(name, text)
    return ("-- Generated by tools/embed.lua from %s.asdl. Do not edit.\nreturn %s\n"):format(name, quote(text))
end

local targets = {
    { asdl = "ast.asdl", out = root .. "wordlet/schema/ast.lua", name = "ast" },
    { asdl = "ir.asdl", out = root .. "wordlet/schema/ir.lua", name = "ir" },
}

local check = arg[1] == "--check"
local stale = {}
for _, target in ipairs(targets) do
    local text = read(root .. target.asdl)
    local generated = module_for(target.name, text)
    local existing = io.open(target.out, "rb")
    local current = existing and existing:read("*a") or nil
    if existing then existing:close() end
    if current ~= generated then
        if check then
            stale[#stale + 1] = target.out
        else
            local f = assert(io.open(target.out, "wb"))
            assert(f:write(generated)); assert(f:close())
            io.stdout:write("wrote " .. target.out .. "\n")
        end
    end
end

if check then
    if #stale > 0 then
        io.stderr:write("stale generated schemas: " .. table.concat(stale, ", ") .. "\nrun: luajit tools/embed.lua\n")
        os.exit(1)
    end
    io.stdout:write("schemas up to date\n")
end
